name: React TypeScript CI/CD to Netlify

on:
  push:
    branches:
      - main, setup  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Install dependencies
        run: npm install 

      - name: Run TypeScript type check
        run: npx tsc --noEmit
        
      - name: Lint codebase and fix errors using prettier
        run: npm run lint:fix

      - name: Build project
        run: npm run build

      # This block uploads the dist file to the GitHub Actions artifacts so it can be used in the deploy job.
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest  
    needs: build 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This block downloads the dist file from the GitHub Actions artifacts.
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: List contents after download
        run: ls -R

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
